#!/usr/bin/env bash
#display process name with wait betwwen iteration
#display signal name when receive it

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
